# Generated by Django 2.2 on 2021-04-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AkiCal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_pic_filename', models.TextField(verbose_name='结果图片路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建的时间')),
            ],
            options={
                'verbose_name': 'AKI计算结果',
                'verbose_name_plural': 'AKI计算结果',
                'db_table': 'aki_cal',
            },
        ),
        migrations.CreateModel(
            name='InputData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='input_data/', verbose_name='上传文件的路由')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建的时间')),
            ],
            options={
                'verbose_name': '输入的数据',
                'verbose_name_plural': '输入的数据',
                'db_table': 'input_data',
            },
        ),
    ]
