# Generated by Django 2.2 on 2021-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data_filename', models.FileField(upload_to='input_data/', verbose_name='上传文件的路由')),
                ('result_pic_filename', models.TextField(default='', verbose_name='结果图片路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建的时间')),
            ],
            options={
                'verbose_name': '文件数据',
                'verbose_name_plural': '文件数据',
                'db_table': 'file_data',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(verbose_name='文件ID')),
                ('idxs', models.TextField(verbose_name='用户索引(第一列的数据)')),
                ('dead_labels', models.TextField(verbose_name='死亡标签(第二列的数据)')),
                ('ages', models.TextField(verbose_name='用户年龄')),
                ('genders', models.TextField(verbose_name='用户性别')),
                ('los_icus', models.TextField(verbose_name='ICU住院时长')),
                ('probas', models.TextField(verbose_name='死亡概率')),
            ],
            options={
                'verbose_name': '院内死亡预测统计数据',
                'verbose_name_plural': '院内死亡预测统计数据',
                'db_table': 'statistics',
            },
        ),
        migrations.DeleteModel(
            name='AkiCal',
        ),
        migrations.DeleteModel(
            name='InputData',
        ),
    ]
