# Generated by Django 2.2 on 2021-04-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20210430_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='me_ves',
            new_name='me_ve',
        ),
        migrations.RenameField(
            model_name='statistics',
            old_name='probas',
            new_name='proba',
        ),
    ]
