# Generated by Django 2.2 on 2021-04-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_auto_20210430_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filedata',
            old_name='result_pic_filename',
            new_name='img_url',
        ),
    ]
