# Generated by Django 2.2 on 2021-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0007_statistics_single_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='file_id',
            field=models.IntegerField(default=0, verbose_name='文件ID'),
        ),
    ]
