# Generated by Django 2.2 on 2021-04-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0008_auto_20210430_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='single_user_id',
            field=models.CharField(default='0', max_length=32, verbose_name='单一用户的ID'),
        ),
    ]
