# Generated by Django 2.2 on 2021-04-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_auto_20210430_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='single_user_id',
            new_name='patient_id',
        ),
    ]
