# Generated by Django 2.2 on 2021-04-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_auto_20210430_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='me_ve',
            field=models.CharField(choices=[('1', '通风'), ('0', '未通风')], default='0', max_length=64, verbose_name='是否机械通风'),
        ),
    ]
